import { Injectable } from '@angular/core';
import {
  Alignment,
  Autoformat,
  BalloonEditor,
  Base64UploadAdapter,
  BlockQuote,
  Bold,
  ClassicEditor,
  CloudServices,
  Essentials,
  FindAndReplace,
  FontBackgroundColor,
  FontColor,
  FontFamily,
  FontSize,
  Heading,
  HorizontalLine,
  Image,
  ImageCaption,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  ImageUpload,
  Indent,
  IndentBlock,
  Italic,
  Link,
  List,
  ListProperties,
  MediaEmbed,
  Mention,
  Paragraph,
  PasteFromOffice,
  PictureEditing,
  RemoveFormat,
  SpecialCharacters,
  SpecialCharactersEssentials,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TableToolbar,
  TextTransformation,
  Underline,
} from 'ckeditor5';

@Injectable({ providedIn: 'root' })
export class CkeditorService {
  public editorEnabled: typeof ClassicEditor | null = null;
  public configEnabled: any;
  public editorDisabled: typeof BalloonEditor | null = null;
  public configDisabled: any;

  constructor() {
    this._setupEditor();
  }

  private _setupEditor() {
    this.editorEnabled = ClassicEditor;
    this.editorDisabled = BalloonEditor;

    // Custom color palette
    const customColors = [
      { color: '#ED1C24', label: 'Custom Red' },
      { color: '#009444', label: 'Custom Green' },
      { color: '#000000', label: 'Black' },
      { color: '#808080', label: 'Gray' },
      { color: '#C0C0C0', label: 'Silver' },
      { color: '#FFFFFF', label: 'White' },
      { color: '#800000', label: 'Maroon' },
      { color: '#FF0000', label: 'Red' },
      { color: '#FFA07A', label: 'Light Salmon' },
      { color: '#DC143C', label: 'Crimson' },
      { color: '#FF6347', label: 'Tomato' },
      { color: '#FF4500', label: 'Orange Red' },
      { color: '#FFD700', label: 'Gold' },
      { color: '#FFFF00', label: 'Yellow' },
      { color: '#ADFF2F', label: 'Green Yellow' },
      { color: '#00FF00', label: 'Lime' },
      { color: '#008000', label: 'Green' },
      { color: '#006400', label: 'Dark Green' },
      { color: '#00FFFF', label: 'Cyan' },
      { color: '#40E0D0', label: 'Turquoise' },
      { color: '#20B2AA', label: 'Light Sea Green' },
      { color: '#000080', label: 'Navy' },
      { color: '#0000FF', label: 'Blue' },
      { color: '#4169E1', label: 'Royal Blue' },
      { color: '#1E90FF', label: 'Dodger Blue' },
      { color: '#87CEFA', label: 'Light Sky Blue' },
      { color: '#B0C4DE', label: 'Light Steel Blue' },
      { color: '#8A2BE2', label: 'Blue Violet' },
      { color: '#4B0082', label: 'Indigo' },
      { color: '#800080', label: 'Purple' },
      { color: '#FF00FF', label: 'Magenta' },
      { color: '#BA55D3', label: 'Medium Orchid' },
      { color: '#DA70D6', label: 'Orchid' },
      { color: '#D8BFD8', label: 'Thistle' },
      { color: '#FF1493', label: 'Deep Pink' },
      { color: '#FF69B4', label: 'Hot Pink' },
      { color: '#FFC0CB', label: 'Pink' },
      { color: '#FAEBD7', label: 'Antique White' },
      { color: '#FFE4C4', label: 'Bisque' },
      { color: '#FFEBCD', label: 'Blanched Almond' },
      { color: '#F5F5DC', label: 'Beige' },
    ];

    this.configEnabled = {
      licenseKey: 'GPL',
      plugins: [
        Alignment,
        Autoformat,
        BlockQuote,
        Bold,
        CloudServices,
        Essentials,
        FindAndReplace,
        FontBackgroundColor,
        FontColor,
        FontFamily,
        FontSize,
        Heading,
        HorizontalLine,
        Image,
        ImageCaption,
        ImageResize,
        ImageStyle,
        ImageToolbar,
        ImageUpload,
        Base64UploadAdapter,
        Indent,
        IndentBlock,
        Italic,
        Link,
        List,
        ListProperties,
        MediaEmbed,
        Mention,
        Paragraph,
        PasteFromOffice,
        PictureEditing,
        RemoveFormat,
        SpecialCharacters,
        SpecialCharactersEssentials,
        Strikethrough,
        Subscript,
        Superscript,
        Table,
        TableToolbar,
        TextTransformation,
        Underline,
      ],
      toolbar: [
        'undo',
        'redo',
        '|',
        'heading',
        '|',
        'bold',
        'italic',
        'underline',
        'removeFormat',
        '|',
        'fontColor',
        'fontBackgroundColor',
        '|',
        'link',
        'insertImage',
        'insertTable',
        'blockQuote',
        'mediaEmbed',
        '|',
        'bulletedList',
        'numberedList',
        '|',
        'outdent',
        'indent',
      ],
      menuBar: {
        isVisible: true,
      },
      heading: {
        options: [
          {
            model: 'paragraph',
            title: 'Paragraph',
            class: 'ck-heading_paragraph',
          },
          {
            model: 'heading1',
            view: 'h1',
            title: 'Heading 1',
            class: 'ck-heading_heading1',
          },
          {
            model: 'heading2',
            view: 'h2',
            title: 'Heading 2',
            class: 'ck-heading_heading2',
          },
          {
            model: 'heading3',
            view: 'h3',
            title: 'Heading 3',
            class: 'ck-heading_heading3',
          },
          {
            model: 'heading4',
            view: 'h4',
            title: 'Heading 4',
            class: 'ck-heading_heading4',
          },
        ],
      },
      image: {
        resizeOptions: [
          {
            name: 'resizeImage:original',
            label: 'Default image width',
            value: null,
          },
          { name: 'resizeImage:50', label: '50% page width', value: '50' },
          { name: 'resizeImage:75', label: '75% page width', value: '75' },
        ],
        toolbar: [
          'imageTextAlternative',
          'toggleImageCaption',
          '|',
          'imageStyle:inline',
          'imageStyle:wrapText',
          'imageStyle:breakText',
          '|',
          'resizeImage',
        ],
      },
      link: {
        addTargetToExternalLinks: true,
        defaultProtocol: 'https://',
      },
      table: {
        contentToolbar: ['tableColumn', 'tableRow', 'mergeTableCells'],
      },
      fontFamily: {
        supportAllValues: true,
      },
      fontSize: {
        options: [10, 12, 14, 'default', 18, 20, 22],
        supportAllValues: true,
      },
      fontColor: {
        colors: customColors,
      },
      fontBackgroundColor: {
        colors: customColors,
      },
    };

    this.configDisabled = {
      licenseKey: 'GPL',
      plugins: [
        Alignment,
        Autoformat,
        BlockQuote,
        Bold,
        CloudServices,
        Essentials,
        FindAndReplace,
        FontBackgroundColor,
        FontColor,
        FontFamily,
        FontSize,
        Heading,
        HorizontalLine,
        Image,
        ImageCaption,
        ImageResize,
        ImageStyle,
        ImageToolbar,
        ImageUpload,
        Base64UploadAdapter,
        Indent,
        IndentBlock,
        Italic,
        Link,
        List,
        ListProperties,
        MediaEmbed,
        Mention,
        Paragraph,
        PasteFromOffice,
        PictureEditing,
        RemoveFormat,
        SpecialCharacters,
        SpecialCharactersEssentials,
        Strikethrough,
        Subscript,
        Superscript,
        Table,
        TableToolbar,
        TextTransformation,
        Underline,
      ],
    };
  }
}
