export const fakeData = {
  base: {
    time: {
      ago: 'Trước',
      just_now: 'Vừa xong',
    },
  },

  // Thanh menu
  menu: {
    home: 'Trang chủ',
    about: 'Giới thiệu',
    domestic_tours: 'Tour trong nước',
    international_tours: 'Tour nước ngoài',
    private_group_tours: 'Tour đoàn riêng',
    services: 'Dịch vụ',
    contact: 'Liên hệ',
  },

  // tab trang chủ
  home: {
    customer: 'Khách hàng',
    best_sale: 'Giá tốt nhất',
    rating: ' lượt đánh giá',
    itinerary: 'Hành trình',
    from: 'Từ',
    price_from: 'Giá chỉ từ',
    no_tour_found: 'Không tìm thấy tour',
  },

  // tab giới thiệu
  about: {},

  // Tab trong nước
  tab_domestic: {
    no_suitable_tour_found: 'Không tìm thấy chuyến đi phù hợp',
    title: 'Tìm chuyến đi phù hợp với bạn tại đây!',
    tab_domestic: 'Trong nước',
    tour: 'Chuyến đi',
    tab_foreign: 'Nước ngoài',
    budget: 'Ngân sách bạn có',
    location: 'Chọn địa điểm',
    departure: 'Điểm đi',
    destination: 'Điểm đến',
    domestic: 'Trong nước',
    international: 'Nước ngoài',
    find_tour: 'Tìm tour',
    reset_tour: 'Đặt lại',
    rating: ' lượt đánh giá',
    itinerary: 'Hành trình',
    from: 'Từ',
    price_from: 'Giá chỉ từ',
  },

  // Tab nước ngoài
  tab_foreign: {
    no_suitable_tour_found: 'Không tìm thấy chuyến đi phù hợp',
    title: 'Tìm chuyến đi phù hợp với bạn tại đây!',
    tab_domestic: 'Trong nước',
    tab_foreign: 'Nước ngoài',
    tour: 'Chuyến đi',
    budget: 'Ngân sách bạn có',
    location: 'Chọn địa điểm',
    departure: 'Điểm đi',
    destination: 'Điểm đến',
    find_tour: 'Tìm tour',
    domestic: 'Trong nước',
    international: 'Nước ngoài',
    reset_tour: 'Đặt lại',
    rating: ' lượt đánh giá',
    itinerary: 'Hành trình',
    from: 'Từ',
    price_from: 'Giá chỉ từ',
  },

  // Tour đoàn riêng
  tab_customer_tour: {
    private_group_tours: 'Tour ghép',
    people_count: 'Số thành viên tham gia',
    estimated_time: 'Thời gian dự kiến',
    estimated_budget: 'Ngân sách dự kiến',
    desired_destination: 'Địa điểm mong muốn',
    note: 'Ghi chú',
    contact_us: 'Hãy liên hệ với chúng tôi',
    name: 'Tên của bạn',
    name_required: 'Tên của bạn là bắt buộc',
    phone: 'Số điện thoại',
    company: 'Công ty',
    phone_required: 'Số điện thoại của bạn là bắt buộc',
    cancel: 'Hủy bỏ',
    submit: 'Gửi',
  },

  // Tour dịch vụ
  tab_service: {
    label_company: 'Công ty',
    title: 'Dịch vụ tư vấn',
    consulting: 'Tư vấn',
    instruction: 'Để thông tin để được tư vấn miễn phí',
    label_name: 'Tên của bạn',
    label_phone: 'Số điện thoại',
    submit_consult_now: 'TƯ VẤN',
    submit_register: 'Đăng kí tư vấn',
    enter_name: 'Nhập tên của bạn',
    validate_required: 'Tên là bắt buộc',
    validate_email: 'Email không hợp lệ',
    validate_phone: 'Số điện thoại là bắt buộc',
    number_of_member: 'Số người tham gia',
    company: 'Công ty',
    estimated_time: 'Thời gian dự kiến',
    note: 'Ghi chú',
  },

  // Tour liên hệ
  tab_contact: {},

  // Chi tiết tour
  tab_tour_detail: {
    tour: 'Chuyến đi',
    your_feedback: 'Đánh giá của bạn',
    please_feedback: 'Vui lòng chọn đánh giá',
    please_enter_content_feedback: 'Vui lòng nhập nội dung đánh giá',
    submit_feedback: 'Gửi đánh giá',
    group_age: 'Nhóm tuổi',
    age: 'Độ tuổi',
    original_price: 'Quy định về giá',
    table_discount: 'Bảng giảm giá',
    type_discount: 'Loại giảm giá',
    description: 'Mô tả',
    value_discount: 'Giá trị giảm',
    if_else: 'Điều kiện',
    table_surcharge: 'Bảng phụ thu',
    name_surcharge: 'Tên phụ thu',
    price_surcharge: 'Số tiền',
    apply_for: 'Áp dụng cho',
    day: 'NGÀY',
    feature_place: 'ĐIỂM NỔI BẬT',
    schedule: 'LỊCH TRÌNH',
    table: 'BẢNG GIÁ',
    service_content: 'DỊCH VỤ BAO GỒM',
    non_service_content: 'DỊCH VỤ KHÔNG BAO GỒM',
    note: 'Ghi chú',
    t_c: 'ĐIỀU KIỆN VÀ QUY ĐỊNH',
    customer_preview: 'KHÁCH HÀNG ĐÁNH GIÁ ',
    booking: 'ĐẶT VÀ GIỮ CHỖ NGAY',
    not_yet_pay: 'Đặt ngay chưa cần thanh toán',
    reviews: 'Đánh giá',
    stars: 'Sao',
    filter_reviews_by: 'Lọc đánh giá theo',
    all: 'Tất cả',
    cancel: 'Hủy bỏ',
    info_contact: 'Thông tin liên lạc',
    submit: 'Gửi',
    address: 'Địa chỉ',
    itinerary: 'Hành trình',
    from: 'Từ',
    price_from: 'Giá chỉ từ',
    full_name: 'Họ và tên',
    enter_name: 'Nhập tên của bạn',
    validate_full_name: 'Họ tên của bạn là bắt buộc',
    phone: 'Số điện thoại',
    validate_phone: 'Số điện thoại của bạn là bắt buộc',
    number_of_member: 'Số thành viên tham gia',
    company: 'Công ty',
    estimated_budget: 'Ngân sách dự kiến',
    no_suitable_tour_found: 'Không tìm thấy chuyến đi phù hợp',
  },
  footer: {
    title: 'Liên Hệ HappySmiles VietNam Travel',
    description:
      "Công ty TNHH <span class='text-[#0b9444] font-medium'>HappySmiles</span> <span class='text-[#ed1c24] font-medium'>VietNam</span> Travel – Cầu nối giữa Công Ty Lữ Hành Quốc Tế tại Việt Nam với công ty tổ chức tour tại nhiều quốc gia trên thế giới.",
  },
  chatbox: {
    title:
      "Xin chào! 👋 <span class='text-[#0b9444] font-bold'>HappySmiles</span> <span class='text-[#ed1c24] font-bold'>VietNam</span> Travel luôn sẵn sàng hỗ trợ bạn qua WhatsApp.",
    description:
      'Vui lòng nhấn vào liên kết bên dưới để trò chuyện với chúng tôi trên WhatsApp.',
    or: 'Hoặc',
    call: 'gọi số',
  },
};

// Bản tiếng anh
export const fakeDataEnglish = {
  base: {
    time: {
      ago: 'Ago',
      just_now: 'Just now',
    },
  },

  // Menu bar
  menu: {
    home: 'Home',
    about: 'About',
    domestic_tours: 'Domestic Tours',
    international_tours: 'International Tours',
    private_group_tours: 'SIC Tour',
    services: 'Services',
    contact: 'Contact',
  },

  // Home tab
  home: {
    customer: 'Customers',
    best_sale: 'Best Deals',
    rating: ' reviews',
    itinerary: 'Itinerary',
    from: 'From',
    price_from: 'Only from',
    no_tour_found: 'No tour found',
  },

  // About tab
  about: {},

  // Domestic tours tab
  tab_domestic: {
    no_suitable_tour_found: 'No suitable tour found',
    tour: 'Tour',
    title: 'Find the right trip for you here!',
    tab_domestic: 'Domestic',
    tab_foreign: 'International',
    budget: 'Your budget',
    location: 'Choose location',
    departure: 'Departure',
    destination: 'Destination',
    find_tour: 'Find tour',
    reset_tour: 'Reset',
    rating: ' reviews',
    itinerary: 'Itinerary',
    domestic: 'Domestic',
    international: 'International',
    from: 'From',
    price_from: 'Price from',
  },

  // International tours tab
  tab_foreign: {
    no_suitable_tour_found: 'No suitable tour found',
    tour: 'Tour',
    title: 'Find the right trip for you here!',
    tab_domestic: 'Domestic',
    tab_foreign: 'International',
    budget: 'Your budget',
    location: 'Choose location',
    departure: 'Departure',
    domestic: 'Domestic',
    international: 'International',
    destination: 'Destination',
    find_tour: 'Find tour',
    reset_tour: 'Reset',
    rating: ' reviews',
    itinerary: 'Itinerary',
    from: 'From',
    price_from: 'Price from',
  },

  // Private group tour tab
  tab_customer_tour: {
    home: 'Home',
    private_group_tours: 'SIC Tour',
    people_count: 'Number of members',
    estimated_time: 'Estimated time',
    estimated_budget: 'Estimated budget',
    desired_destination: 'Desired destination',
    note: 'Note',
    contact_us: 'Contact us',
    name: 'Your name',
    name_required: 'Your name is required',
    phone: 'Phone number',
    company: 'Company',
    phone_required: 'Your phone number is required',
    cancel: 'Cancel',
    submit: 'Submit',
  },

  // Services tab
  tab_service: {
    label_company: 'Company',
    title: 'Consulting Service',
    consulting: 'Consulting',
    instruction: 'Leave your information to get free consultation',
    label_name: 'Your name',
    label_phone: 'Phone number',
    submit_consult_now: 'CONSULT NOW',
    submit_register: 'Register for consultation',
    enter_name: 'Enter your name',
    validate_required: 'Name is required',
    validate_email: 'Invalid email',
    validate_phone: 'Phone number is required',
    number_of_member: 'Number of members',
    company: 'Company',
    estimated_time: 'Estimated time',
    note: 'Note',
  },

  // Contact tab
  tab_contact: {},

  // Tour detail tab
  tab_tour_detail: {
    tour: 'Tour',
    your_feedback: 'Your feedback',
    please_feedback: 'Please select a rating',
    please_enter_content_feedback: 'Please enter feedback content',
    submit_feedback: 'Submit feedback',
    group_age: 'Age group',
    age: 'Age',
    original_price: 'Price policy',
    table_discount: 'Discount table',
    type_discount: 'Discount type',
    description: 'Description',
    value_discount: 'Discount value',
    if_else: 'Conditions',
    table_surcharge: 'Surcharge table',
    name_surcharge: 'Surcharge name',
    price_surcharge: 'Amount',
    apply_for: 'Apply for',
    day: 'DAY',
    feature_place: 'HIGHLIGHTS',
    schedule: 'ITINERARY',
    table: 'PRICE TABLE',
    service_content: 'INCLUDED SERVICES',
    non_service_content: 'EXCLUDED SERVICES',
    note: 'Note',
    t_c: 'TERMS & CONDITIONS',
    customer_preview: 'CUSTOMER REVIEWS',
    booking: 'BOOK & RESERVE NOW',
    not_yet_pay: 'Book now, pay later',
    reviews: 'Reviews',
    stars: 'Stars',
    filter_reviews_by: 'Filter reviews by',
    all: 'All',
    cancel: 'Cancel',
    info_contact: 'Contact Information',
    submit: 'Submit',
    address: 'Address',
    itinerary: 'Itinerary',
    from: 'From',
    price_from: 'Price from',
    full_name: 'Full name',
    enter_name: 'Enter your name',
    validate_full_name: 'Full name is required',
    phone: 'Phone number',
    validate_phone: 'Your phone number is required',
    number_of_member: 'Number of members',
    company: 'Company',
    estimated_budget: 'Estimated budget',
    no_suitable_tour_found: 'No suitable tour found',
  },

  footer: {
    title: 'Contact HappySmiles VietNam Travel',
    description:
      "<span class='text-[#ed1c24] font-medium'> HappySmiles VietNam</span> Travel - A Channel connects Vietnam DMC and Travel Agents in The World.",
  },

  chatbox: {
    title:
      "Hello! 👋<span class='text-[#ed1c24] font-bold'> HappySmiles VietNam</span> Travel is always ready to support you via WhatsApp.",
    description: 'Please click the link below to chat with us on WhatsApp.',
    or: 'Or',
    call: 'call',
  },
};
