export const fakeData = {
  base: {
    time: {
      ago: 'Trước',
      just_now: 'Vừa xong',
    },
  },
  menu: {
    home: 'Trang chủ',
    about: 'Giới thiệu',
    domestic_tours: 'Tour trong nước',
    international_tours: 'Tour nước ngoài',
    private_group_tours: 'Tour đoàn riêng',
    services: 'Dịch vụ',
    contact: 'Liên hệ',
    language: 'Tiếng Việt',
  },

  home: {
    customer: 'Khách hàng',
    best_sale: 'Giá tốt nhất',
    rating: ' lượt đánh giá',
    itinerary: 'Hành trình',
    from: 'Từ',
    price_from: 'Giá chỉ từ',
  },
  about: {},
  tab_domestic: {
    no_suitable_tour_found: 'Không tìm thấy chuyến đi phù hợp',
    title: 'Tìm chuyến đi phù hợp với bạn tại đây!',
    tab_domestic: 'Trong nước',
    tab_foreign: 'Nước ngoài',
    budget: 'Ngân sách bạn có',
    location: 'Chọn địa điểm',
    departure: 'Điểm đi',
    destination: 'Điểm đến',
    find_tour: 'Tìm tour',
    reset_tour: 'Đặt lại',
    rating: ' lượt đánh giá',
    itinerary: 'Hành trình',
    from: 'Từ',
    price_from: 'Giá chỉ từ',
  },
  tab_foreign: {
    no_suitable_tour_found: 'Không tìm thấy chuyến đi phù hợp',
    title: 'Tìm chuyến đi phù hợp với bạn tại đây!',
    tab_domestic: 'Trong nước',
    tab_foreign: 'Nước ngoài',
    budget: 'Ngân sách bạn có',
    location: 'Chọn địa điểm',
    departure: 'Điểm đi',
    destination: 'Điểm đến',
    find_tour: 'Tìm tour',
    reset_tour: 'Đặt lại',
    rating: ' lượt đánh giá',
    itinerary: 'Hành trình',
    from: 'Từ',
    price_from: 'Giá chỉ từ',
  },
  tab_customer_tour: {
    people_count: 'Số thành viên tham gia',
    estimated_time: 'Thời gian dự kiến',
    estimated_budget: 'Ngân sách dự kiến',
    desired_destination: 'Địa điểm mong muốn',
    note: 'Ghi chú',
    contact_us: 'Hãy liên hệ với chúng tôi',
    name_required: 'Tên của bạn là bắt buộc',
    phone_required: 'Số điện thoại của bạn là bắt buộc',
    cancel: 'Hủy bỏ',
    submit: 'Gửi',
  },
  tab_service: {},
  tab_contact: {
    label_company: 'Công ty',
    title: 'Dịch vụ tư vấn',
    consulting: 'Tư vấn',
    instruction: 'Để thông tin để được tư vấn miễn phí',
    label_name: 'Tên của bạn',
    label_phone: 'Số điện thoại',
    label_email: 'Email',
    label_note: 'Ghi chú',
    submit_consult_now: 'TƯ VẤN',
    submit_register: 'Đăng kí tư vấn',
    enter_name: 'Nhập tên của bạn',
    validate_required: 'Tên là bắt buộc',
    validate_email: 'Email không hợp lệ',
    validate_phone: 'Số điện thoại là bắt buộc',
  },

  tab_tour_detail: {
    home: 'Trang chủ',
    tour: 'Chuyến đi',
    your_feedback: 'Đánh giá của bạn',
    please_feedback: 'Vui lòng chọn đánh giá',
    please_enter_content_feedback: 'Vui lòng nhập nội dung đánh giá',
    submit_feedback: 'Gửi đánh giá',
    group_age: 'Nhóm tuổi',
    age: 'Độ tuổi',
    original_price: 'Quy định về giá',
    table_discount: 'Bảng giảm giá',
    type_discount: 'Loại giảm giá',
    description: 'Mô tả',
    value_discount: 'Giá trị giảm',
    if_else: 'Điều kiện',
    table_surcharge: 'Bảng phụ thu',
    name_surcharge: 'Tên phụ thu',
    price_surcharge: 'Số tiền',
    apply_for: 'Áp dụng cho',
    day: 'NGÀY',
    feature_place: 'ĐIỂM NỔI BẬT',
    schedule: 'LỊCH TRÌNH',
    table: 'BẢNG GIÁ',
    service_content: 'DỊCH VỤ BAO GỒM',
    non_service_content: 'DỊCH VỤ KHÔNG BAO GỒM',
    note: 'Ghi chú',
    t_c: 'ĐIỀU KIỆN VÀ QUY ĐỊNH',
    customer_preview: 'KHÁCH HÀNG ĐÁNH GIÁ ',
    booking: 'ĐẶT VÀ GIỮ CHỖ NGAY',
    not_yet_pay: 'Đặt ngay chưa cần thanh toán',
    reviews: 'Đánh giá',
    stars: 'Sao',
    filter_reviews_by: 'Lọc đánh giá theo',
    all: 'Tất cả',
    cancel: 'Hủy bỏ',
    info_contact: 'Thông tin liên lạc',
    submit: 'Gửi',
    address: 'Địa chỉ',
    itinerary: 'Hành trình',
    from: 'Từ',
    price_from: 'Giá chỉ từ',
    full_name: 'Họ và tên',
    enter_name: 'Nhập tên của bạn',
    validate_full_name: 'Họ tên của bạn là bắt buộc',
    phone: 'Số điện thoại',
    validate_phone: 'Số điện thoại của bạn là bắt buộc',
    number_of_member: 'Số thành viên tham gia',
    company: 'Công ty',
    estimated_budget: 'Ngân sách dự kiến',
    no_suitable_tour_found: 'Không tìm thấy chuyến đi phù hợp',
  },
  breadcrumb: {
    home: 'Trang chủ',
    private_group_tours: 'Tour đoàn riêng',
  },
  footer: {
    title: 'Liên Hệ HappySmiles VietNam Travel',
    description:
      "Công ty TNHH <span class='text-[#0b9444] font-medium'>HappySmiles</span> <span class='text-[#ed1c24] font-medium'>VietNam</span> Travel – Cầu nối giữa Công Ty Lữ Hành Quốc Tế tại Việt Nam với công ty tổ chức tour tại nhiều quốc gia trên thế giới.",
  },
  chatbox: {
    title:
      "Xin chào! 👋 <span class='text-[#0b9444] font-bold'>HappySmiles</span> <span class='text-[#ed1c24] font-bold'>VietNam</span> Travel luôn sẵn sàng hỗ trợ bạn qua WhatsApp.",
    description:
      'Vui lòng nhấn vào liên kết bên dưới để trò chuyện với chúng tôi trên WhatsApp.',
    or: 'Hoặc',
    call: 'gọi số',
  },
};
