import { TourResDTO } from './interface';

export const MOCK_TOURS: TourResDTO[] = [
  {
    id: 1,
    tourId: 1001,
    title: 'Khám phá Đà Lạt 3N2Đ',
    star: 4.5,
    numberComment: 112,
    destination: ['Đà Lạt', 'Lâm Đồng'],
    originalPrice: 4000000,
    discount: 500000,
    finalPrice: 3500000,
    stayDate: '3N2Đ',
    location: { id: 1, name: 'TP. Hồ Chí Minh' },
    startingPoints: [
      { id: 1, name: 'TP. Hồ Chí Minh' },
      { id: 2, name: 'Biên Hòa' },
    ],
    highlight: 'Thung lũng tình yêu, Đồi chè Cầu Đất, Hồ Tuyền Lâm',
    service: 'Xe đưa đón, Hướng dẫn viên, Ăn uống, Vé tham quan',
    nonService: 'Chi phí cá nhân, VAT, Tip HDV',
    regulation: 'Hủy trước 7 ngày mất 50%, sau 3 ngày mất 100%',
    note: 'Mang theo áo ấm vì thời tiết lạnh',
    imageUrl: [
      'https://source.unsplash.com/featured/?dalat',
      'https://source.unsplash.com/featured/?lamdong',
    ],
    language: { id: 1, code: 'vi', name: 'Tiếng Việt' },
  },
  {
    id: 2,
    tourId: 1002,
    title: 'Du lịch Singapore - Malaysia 5N4Đ',
    star: 4.8,
    numberComment: 78,
    destination: ['Singapore', 'Kuala Lumpur'],
    originalPrice: 12000000,
    discount: 2000000,
    finalPrice: 10000000,
    stayDate: '5N4Đ',
    location: { id: 2, name: 'Hà Nội' },
    startingPoints: [{ id: 2, name: 'Hà Nội' }],
    highlight: 'Vườn Garden by the Bay, Twin Towers, phố Orchard',
    service: 'Vé máy bay khứ hồi, khách sạn, ăn uống, vé tham quan',
    nonService: 'Hành lý quá cước, chi phí cá nhân',
    regulation: 'Hủy trước 10 ngày mất 30%, sau 5 ngày mất 100%',
    note: 'Mang theo hộ chiếu còn hạn 6 tháng',
    imageUrl: [
      'https://source.unsplash.com/featured/?singapore',
      'https://source.unsplash.com/featured/?malaysia',
    ],
    language: { id: 1, code: 'vi', name: 'Tiếng Việt' },
  },
  {
    id: 3,
    tourId: 1003,
    title: 'Du lịch Huế - Đà Nẵng - Hội An 4N3Đ',
    star: 4.6,
    numberComment: 45,
    destination: ['Huế', 'Đà Nẵng', 'Hội An'],
    originalPrice: 5500000,
    discount: 500000,
    finalPrice: 5000000,
    stayDate: '4N3Đ',
    location: { id: 3, name: 'Cần Thơ' },
    startingPoints: [{ id: 3, name: 'Cần Thơ' }],
    highlight: 'Cố đô Huế, Bà Nà Hills, phố cổ Hội An',
    service: 'Khách sạn 4*, xe máy lạnh, vé tham quan, ăn 3 bữa',
    nonService: 'Đồ uống riêng, tip HDV',
    regulation: 'Hủy tour mất 30%, sau 2 ngày mất 100%',
    note: 'Thời tiết nắng nóng, nên mang mũ và nước uống',
    imageUrl: [
      'https://source.unsplash.com/featured/?hue',
      'https://source.unsplash.com/featured/?hoian',
    ],
    language: { id: 1, code: 'vi', name: 'Tiếng Việt' },
  },
];
